### ISSUE TITLE
Don't crash on syntax error

### ISSUE THREAD

**Issue by ivan-kleshnin** [alexmingoia/gulp-jsx#8]
Currently this line
```javascript
file.contents = new Buffer(jsx.transform(file.contents.toString('utf8'), options));
```

throws at syntax error in async mode (so even **gulp-plumber** can't help) which crashes all **gulp** tasks (including watchers). Restarts are expensive, so we should find another option. Perhaps we should add something like this:

```javascript
try {
  file.contents = new Buffer(jsx.transform(file.contents.toString('utf8'), options));
} catch (err) {
  next(err.message);
}
```

---
I use gulp-jsx in this way:

```javascript
Gulp.task("build", function() {
  return Gulp.src("src/**/*.js")
    .pipe(gulpPlumber({errorHandler: !exitOnError})) // we still want "global stops" at release time...
    .pipe(gulpCached("build"))
    .pipe(gulpJsx(jsxOptions))
    .pipe(gulpPlumber.stop())
    .pipe(Gulp.dest("build"));
});
```

So at error we either log error and continue to build, or crash. The better option would be to skip this exact `build` step (because `build` triggers other stuff) but I can't find any option to do it. Any clues?

**Comment by alexmingoia** [comment]
Yes, the transform should be wrapped in a try/catch
